# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  displayName: Build  
  inputs:
    targetType: 'inline'
    script: | 
      CIRCLE_TAG=1.18.1 ./scripts/build-release.sh

- task: UniversalPackages@0
  displayName: Release  
  enabled: false
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '7720f8d2-bf64-47d9-8b10-53f21220d54d/9ba7201b-e25d-4afc-b55b-6ad212a1516d'
    vstsFeedPackagePublish: 'terraform-provider-keycloak'
    versionOption: 'patch'
    packagePublishDescription: 'Embrace Fork of terraform-provider-keycloak, https://github.com/embracesbs/terraform-provider-keycloak'

